### ISSUE TITLE
S3 driver is limiting AWS features

### ISSUE THREAD

**Issue by anantab** [Slynova-Org/node-flydrive#16]
I am not sure why AWS driver  takes only 3 config options in constructor.  
```  
accessKeyId: config.key,
secretAccessKey: config.secret,
region: config.region 
```

AWS s3 sdk takes a lot of other configuration options and this driver is limiting features provided by AWS.

I was looking at using local s3 server provided by Atlassian localstack  with Adonis Framework. But  I could not specify s3  endpoint with the driver. It would be same issue if someone wanted to set proxy config. I think the driver should take all s3 Parameters in config and not just 3. Better option would to allow injecting  s3 Object to the driver so anyone could create their s3 object with their custom configuration and pass it to driver.

**Comment by RomainLanz** [comment]
Hey @anantab! 👋 

May you share a PR for this?

**Comment by antwaanvh** [comment]
This should work. #24
