### ISSUE TITLE
Test(s) failure

### ISSUE THREAD

**Issue by antwaanvh** [Slynova-Org/node-flydrive#20]
On a clean fork the following tests fail. 
> Yes, .env file has SES_KEY, SES_SECRET, SES_BUCKET & SES_REGION have values 😃

![screen shot 2018-01-29 at 5 41 18 pm](https://user-images.githubusercontent.com/1783825/35538524-3abceba8-051c-11e8-89ad-7412d920b767.png)

Removing lines 211-213 from AwsS3.js slightly remedies the issue...
https://github.com/Slynova-Org/node-flydrive/blob/112ec6385199a3ef78f0c522ed3520dc4d980d9b/src/Drivers/AwsS3.js#L207-L216

but then this test fails
![screen shot 2018-01-29 at 5 41 35 pm](https://user-images.githubusercontent.com/1783825/35538850-452b3940-051d-11e8-9daa-1924cd3c2de6.png)

It seems as though, at least in my case, this 
https://github.com/Slynova-Org/node-flydrive/blob/112ec6385199a3ef78f0c522ed3520dc4d980d9b/src/Drivers/AwsS3.js#L211 will always be truthy.

![screen shot 2018-01-29 at 5 56 08 pm](https://user-images.githubusercontent.com/1783825/35539532-fe36d35c-051f-11e8-84f6-f19a0998a65a.png)

**Comment by RomainLanz** [comment]
Hey @antwaanvh ! 👋 

I have no issue running my test on my computer.
I am not an expert on S3 but I think the output depends on how you configured your S3 Bucket.

**Comment by antwaanvh** [comment]
Hi @RomainLanz,

Is this the develop branch?
I haven't done anything out of the ordinary when setting up a S3 bucket. Is there anything in particular that you do when setting up a bucket?

Thanks 😄
