### ISSUE TITLE
a list() method

### ISSUE THREAD

**Issue by thsteinmetz** [Slynova-Org/node-flydrive#34]
I personally have use for a `list()` method, specifically for S3 buckets. I've written this in other projects but I would like to make a PR for this feature on the S3 driver. 

Is this something you think would be accepted? I could write the equivalent for the filesystem driver too, but I would use something like the klaw package. Thoughts?

**Comment by RomainLanz** [comment]
Hey @thsteinmetz! 👋 

What the purpose of this method?

**Comment by thsteinmetz** [comment]
@RomainLanz It is just a list of all the files in the bucket/directory. My specific usecase is that I have to iterate over all the files in a bucket and find those that contain certain strings in their file name.

**Comment by thsteinmetz** [comment]
@RomainLanz [This](https://github.com/thsteinmetz/node-flydrive/blob/9fb11509d5d08fdb7a9b719b525e1a8f91faaeb8/src/Drivers/AwsS3.js#L319) is what I am thinking. 

[Test](https://github.com/thsteinmetz/node-flydrive/blob/9fb11509d5d08fdb7a9b719b525e1a8f91faaeb8/tests/unit/s3-driver.spec.js#L156) for it.

If you think you'd merge something like this in I'll make a similar feature for the filesystem driver and create a PR.

**Comment by RomainLanz** [comment]
Closing in favor of the related PR.
