### ISSUE TITLE
Dynamic config object

### ISSUE THREAD

**Issue by molobala** [Slynova-Org/node-flydrive#46]
What if we could use drivers dynamically, that's to say we can change authenfiticated user in case of FTP, AWS Driver for instance in runtime  

Imagine my application need to store data to users ftp, so with the current config object I dont see any way to change the authentification credentials  

Would be good if al driver with authentification provides a method `with(credentials|config)` so that we can change dynamically configuration object, or maybe the Storage manager provide a way to change the configuration when getting the driver instance in the method `disk(name)`

**Comment by RomainLanz** [comment]
Hey @molobala! 👋 

Would be happy to accept a PR that manage this 👍

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
